postgres:
    dialect: postgres
    datasource: host=postgres dbname=test sslmode=disable user=postgres password=coolpasswordkid
    dir: test-migrations

mysql:
    dialect: mysql
    datasource: root:coolpasswordkid@mysql/test?parseTime=true
    dir: test-migrations

mysql_noflag:
    dialect: mysql
    datasource: root:coolpasswordkid@mysql/test
    dir: test-migrations

sqlite:
    dialect: sqlite3
    datasource: test.db
    dir: test-migrations
    table: migrations
